Use script. Add -eTV, magic -A. Remove -fyYX. Fix double rm. Bourne fix

diff --git a/sudox b/sudox
--- a/sudox
+++ b/sudox
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env sh
 # (C) Martin V\"ath <martin@mvath.de>
 set -u
 set -f
@@ -10,7 +10,6 @@ unset IFS BASH_ENV ENV SHELL_OPTS || exit 2
 BASH_ENV=
 ENV=
 SHELL_OPTS=
-OPTIND=1
 [ -z "$BASH_ENV$ENV$SHELL_OPTS" ] || exit 2
 
 # Actually, these are two scripts: The "main" script is documented
@@ -22,12 +21,16 @@ OPTIND=1
 # Currently, the syntax for the remote side is as follows:
 #
 # "$0" '-remotecall' "$SHELL" display1 display2 ... '-dispend;' \
-#        'Name of socket used to transfer data'|'' \
-#        [chown tty newuser:group]|'' \
+#        'Name of fifo used to transfer data'|'' \
 #        command [args for command]
 #
-# The actual authorization data is not passed as an arg but via the socket.
+# The actual authorization data is not passed as an arg but via the fifo.
 # First, some helper functions needed for both parts of the script:
+
+Version() {
+	Echo 'sudox 4.0'
+	exit 0
+}
 
 Echo() {
 	printf '%s\n' "$*"
@@ -73,26 +76,28 @@ Troyan() {
 }
 
 ReadTransfer() {
-	read -r count || Troyan 'unreadable socket'
+	read -r count || Troyan 'unreadable fifo'
 	(	unset LC_ALL
 		LC_COLLATE=C
 		case ${count:-x} in
-		*[!0-9]*)	false;;
+		*[!0-9]*)
+			false;;
 		esac
-	) || Troyan 'corruption with socket'
+	) || Troyan 'corruption with fifo'
 	if [ "$count" -gt 0 ]
 	then	transfer=`dd bs="$count" count=1 2>/dev/null && echo x` || \
-			Troyan 'corruption with socket'
+			Troyan 'corruption with fifo'
 		transfer=${transfer%x}
-		[ $count -eq ${#transfer} ] || Troyan 'corruption with socket'
+		[ $count -eq ${#transfer} ] || Troyan 'corruption with fifo'
 	fi
+	eval "AddAuthorities $transfer"
+	:
 }
 
 ParseSocket() {
 	[ -z "${1:++}" ] && return
-	test -p "$1" || Troyan "no socket $1"
-	ReadTransfer <"$1"
-	eval "AddAuthorities $transfer"
+	test -p "$1" || Troyan "no fifo $1"
+	ReadTransfer <"$1" || exit
 }
 
 if [ x"${1-}" = x'-remotecall' ]
@@ -110,88 +115,64 @@ then	shift
 	done
 	ParseSocket "$1"
 	shift
-	SUDO_COMMAND=
-	unset SUDO_COMMAND
-	if [ -n "${1:++}" ]
-	then	"$1" "-v" "--" "$3" "$2" || Fatal \
-"Could not change permissions of tty $2 to $3"
-		shift 3
-	else	shift
-	fi
+	SUDO_COMMAND=${*-}
 	DoExec ${1+"$@"}
 fi
 
 # Now the main part of the script (i.e. the "server" side called by the user):
 
 Usage() {
-	name=${0##*/}
-	Echo "Usage: $name [options] [user [command]]
+	Echo "Usage: ${0##/} [options] [user [command]]
 Similar to sudo -H -u user -s -- but transfer also X authority data.
 Most options are passed to sudo, essentially with the following exceptions:
-
--f Start even if tmux/screen seems to be running.
-   This might be a security risk.
--s Start a tmux/screen session. Think about combining with -y or -Y
--S As -s but prefer screen over tmux
--Y Chown (possibly using sudo once more) the attached \$TTY to the
-   new user/group before the actual execution.
-   If you use $name to switch from an \"untrusted\" user to a \"trusted\" user
-   this increases your security, because then what you type in the new session
-   cannot be logged from the \"untrusted\" user, unless a log demon was
-   started from within the current session before $name is executed.
-   However, if you use $name to switch from a \"trusted\" user to an
-   \"untrusted\" user, the untrusted user might log what you enter in your
-   session even when $name is finished. As a workaround you might use:
--y As -Y but after finishing use chown (possibly using sudo once more) to
-   restore the original ownership of the attached \$TTY. Be aware,
-   however, that this can only work if the process is not killed and that
-   the remote user still has the privileges to log the password you enter
-   in this sudo call.
+-l Clear STY/TMUX for the command/session (mnemonic: login environment)
+-e Currently identical to -l; this might change in future releases
+-p Without this option, -A is passed to sudo when SUDO_ASKPASS is set
+-T Do not call \"script\" to open a new tty; security risk if interactive.
+   If -xT are used but not -s/-S, then act similar to sudo -H -u user --
+   This is useful if special entries in /etc/sudoers should be prepared.
+-s Start a tmux (fallback to screen) session
+-S Start a screen (fallback to tmux) session
 -x Do not transfer any X authority data
--X Execute command as file, i.e. behave as sudo -H -u user -- (without -s)
-   Useful for entries in /etc/sudoers. This option implies -x
 -u Generate only an untrusted permission. (This requires that your xorg-server
    was compiled with --enable-xcsecurity.) You might combine this with:
 -t TIMEOUT (in seconds). Time for which the untrusted permission is valid.
-   The value 0 (default) means: forever.
+   The value 0 (default) means: forever
 -U Delete all X authority data on the remote side - similar to -u -t 1
+-V Print version
 -h Print this help"
 	exit ${1:-1}
 }
 
-ClearMyTraps() {
-	my_traps='-'
-	trap - EXIT HUP INT TERM
-}
-ClearMyTraps
-AddTrap() {
-	if [ x"$my_traps" = x'-' ]
-	then	Push -c my_traps ${1+"$@"}
-		trap MyTrap EXIT HUP INT TERM
-	else	Push my_traps ${1+"$@"}
-	fi
+tmpdir=
+RmTemp() {
+	trap : EXIT HUP INT TERM
+	[ -n "${tmpdir:++}" ] && test -d "$tmpdir" && rm -rf -- "$tmpdir"
+	tmpdir=
+	ClearTrap
 }
 
 retvalue=0
 MyTrap() {
-	trap : EXIT HUP INT TERM
-	eval "$my_traps"
-	ClearMyTraps
+	RmTemp
 	exit $retvalue
 }
 
-tmpdir=
-RmTemp() {
-	[ -n "${tmpdir:++}" ] && test -d "$tmpdir" && rm -rf -- "$tmpdir"
-	tmpdir=
+SetTrap() {
+	trap MyTrap EXIT HUP INT TERM
+}
+
+ClearTrap() {
+	trap - EXIT HUP INT TERM
 }
 
 MkTemp() {
 	[ -n "${tmpdir:++}" ] && return
-	AddTrap RmTemp
+	SetTrap
 	if command -v mktemp >/dev/null 2>&1
 	then	tmpdir=`umask 077 && mktemp -d -- "${TMPDIR:-/tmp}/${0##*/}.XXXXXXXX"` \
 			&& [ -n "${tmpdir:++}" ] && test -d "$tmpdir" && return
+		ClearTrap
 		ErrMessage 'cannot create temporary directory'
 		return 2
 	fi
@@ -223,36 +204,38 @@ MkTemp() {
 		mkdir -m 700 -- "$t" && tmpdir=$t && return
 		c=$(( $c + 1 ))
 	done
+	ClearTrap
 	ErrMessage 'cannot create temporary directory'
 	return 2
 }
 
 # Parse options
 
+askpass=:
 untrusted=
 timeout=0
 nox=false
-noshell=false
 screen=
-chownpts=
-force=false
+script=:
+clear=false
 Push -c sudoargs
-while getopts "fUut:xXHsSyY?ha:c:p:VlLkKbPS" opt
+OPTIND=1
+while getopts "leTUut:xHsSyYh?Va:c:g:r:inkKbPAE" opt
 do	case $opt in
-	f)	force=:;;
+	l|e)	clear=:;;
+	p)	askpass=false;;
+	T)	script=false;;
 	U)	untrusted=2;;
 	u)	untrusted=1;;
 	t)	timeout=$OPTARG;;
 	x)	nox=:;;
-	X)	nox=:
-		noshell=:;;
 	s)	screen='tmux screen';;
 	S)	screen='screen tmux';;
-	y)	chownpts=1;;
-	Y)	chownpts=0;;
 	H)	:;;
+	V)	Version;;
 	[h?])	Usage;;
-	[acp])	Push sudoargs "-$opt" "$OPTARG";;
+	[acgpr])
+		Push sudoargs "-$opt" "$OPTARG";;
 	*)	Push sudoargs "-$opt";;
 	esac
 done
@@ -260,28 +243,31 @@ shift $(( $OPTIND - 1 ))
 
 # Parse remainder
 
-Push sudoargs "-H"
-remoteuse='root'
+Push sudoargs -H
+remoteuse=root
 if [ $# -gt 0 ]
 then	remoteuse=$1
 	shift
 	Push sudoargs "-u" "$remoteuse"
 fi
-command -v id >/dev/null 2>&1 || Fatal 'Cannot find id'
-if [ x"`id -un`" = x"$remoteuse" ]
-then	Warning "Warning: remote user is the current user. Probably this
-is a mistake - therefore, no X authorization data is modified.
-"
+
+# clear STY/TMUX
+
+! $clear || unset STY TMUX
+
+# Check whether we want to change to the current user
+
+currid=`id -un` && [ -n "$currid" ] || Fatal 'cannot get id'
+if [ x"$currid" = x"$remoteuse" ]
+then	Warning 'warning: remote user is the current user.
+Assuming that this is a mistake: not modifying X authorization data
+'
 	DoExec ${1+"$@"}
 fi
 
-$force || [ -z "${STY:++}${TMUX:++}" ] || \
-	Fatal '"screen" or "tmux" seems to be running.
-Using su within a screen session is a security risk, because the original
-user might have access from other screen sessions.
-Better "exit" the screen session first.
-Use option -f if you are willing to take the risk. Exiting for now.'
+# Check for SUDO_ASKPASS
 
+! $askpass || [ -z "${SUDO_ASKPASS:++}" ] || Push sudoargs -A
 
 # Generate remote command and data to transfer
 
@@ -318,9 +304,11 @@ then	# Generate list of all displays to transfer
 	# Generate authorization data in $transfer
 	if [ -n "${untrusted:++}" ]
 	then	if [ x"$untrusted" = x'1' ] && [ -n "${DISPLAY:++}" ]
-		then	MkTemp
+		then	MkTemp || exit
 			a=$tmpdir/untrusted
-			:>"$a" || Fatal "cannot create $a"
+			(
+				umask 077 && : >"$a"
+			) || Fatal "cannot create $a"
 			xauth -q -f "$a" generate "$DISPLAY" . untrusted \
 				timeout "$timeout" || Fatal \
 'failed to create untrusted permissions.
@@ -329,7 +317,7 @@ Perhaps your xorg-server was compiled without --enable-xcsecurity'
 			&& [ -n "${b:++}" ] || Fatal \
 'failed to source data with untrusted permission'
 			rm -- "$a"
-			Push -c transfer "$b"
+			Push transfer "$b"
 		fi
 	else	CalcTransfer
 	fi
@@ -338,110 +326,88 @@ Perhaps your xorg-server was compiled without --enable-xcsecurity'
 	unset XAUTHORITY
 fi
 
-MyChown() {
-	if [ "$oriuser" -eq 0 ]
-	then	chown -v -- "$1" "$ttyvalue"
-	else	MsgErr "sudo chown $1 $ttyvalue"
-		sudo "$chownprg" -v -- "$1" "$ttyvalue"
-	fi || Fatal "failed: chown $1 $ttyvalue"
-}
-
-changeto=
-if [ -n "${chownpts:++}" ]
-then	ttyvalue=`tty` && [ -n "${ttyvalue:++}" ] && \
-	if command -v readlink >/dev/null 2>&1
-	then	ttyvalue=`readlink -f -- "$ttyvalue"` && \
-		[ -n "${ttyvalue:++}" ] && ! test -h "$ttyvalue"
-	fi && test -c "$ttyvalue" || Fatal 'cannot determine tty'
-	oriuser=`id -u`
-	chownprg=`export PATH='/bin:/sbin:/usr/bin:/usr/sbin'
-		command -v chown 2>/dev/null` && \
-		[ -n "${chownprg:++}" ] || Fatal 'cannot find chown'
-	remotegroup=`id -g -- "$remoteuse"` && \
-		[ -n "${remotegroup:++}" ] \
-			|| Fatal "User $remoteuse has no group"
-	# If we change TO root, we change the tty permissions on the remote side:
-	# This way, we need one call less to sudo.
-	if [ x"$remoteuse" != x'root' ] || $noshell
-	then
-		MyChown "$remoteuse:$remotegroup"
-	else	changeto=$remoteuse:$remotegroup
-	fi
-fi
-
-# Generate socket
+# Generate fifo
 if [ -z "${transfer:++}" ]
-then	socket=
+then	fifo=
 	RmTemp
-	ClearMyTraps
 else	MkTemp
 	chmod -- 711 "$tmpdir"
-	socket=$tmpdir/socket
-	( umask 000 && mkfifo -- "$socket" ) \
-		|| Fatal "cannot create socket $socket"
+	fifo=$tmpdir/fifo
+	( umask 000 && mkfifo -- "$fifo" ) \
+		|| Fatal "cannot create fifo $fifo"
 fi
-
-# Generate ResetTty trap for -y
-
-ResetTty() {
-	id=`id -g`
-	MyChown "$oriuser:$id"
-}
-[ x"$chownpts" = x'1' ] && AddTrap 'ResetTty'
 
 # Generate remote command:
 
 GenRemote() {
 	Push sudoargs '--'
-	$nox && $noshell && [ -z "${ttyvalue:++}" ] && return
+	! $nox || return 0
 	Push sudoargs "$1"
 	eval "set -- a $displays"
 	shift
-	Push sudoargs '-remotecall' "$SHELL" ${1+"$@"} '-dispend;'
-	Push sudoargs "$socket"
-	if [ -n "${changeto:++}" ]
-	then	Push sudoargs "$chownprg" "$ttyvalue" "$changeto"
-	else	Push sudoargs ''
-	fi
+	Push sudoargs '-remotecall' "${SHELL:-sh}" ${1+"$@"} '-dispend;'
+	Push sudoargs "$fifo"
 }
 GenRemote "$0"
 
+Push -c sudocmd
 if [ -n "${screen:++}" ]
 then	for screenprg in $screen
 	do	if screen=`export PATH='/bin:/sbin:/usr/bin:/usr/sbin'
 		command -v "$screenprg" 2>/dev/null` && [ -n "${screen:++}" ]
-		then	Push sudoargs "$screen" '--'
-			case $screenprg in
+		then	case $screenprg in
 			screen)
 				unset STY;;
 			tmux)
 				unset TMUX;;
 			esac
+			if $script
+			then	Push sudocmd exec "$screen" '--'
+			else	Push sudoargs "$screen" '--'
+			fi
 			screen=
 			break
 		fi
 	done
 	[ -z "${screen:++}" ] || Fatal 'tmux/screen not found'
 fi
-
-Push sudoargs ${1+"$@"}
+if $script
+then	script=`export PATH='/bin:/sbin:/usr/bin:/usr/sbin'
+	command -v script 2>/dev/null` && [ -n "$script" ] \
+		|| Fatal '"script" not found'
+	Push sudocmd ${1+"$@"}
+	Push sudoargs "$script" -q -e \
+		${sudocmd:+-c} ${sudocmd:+"$sudocmd"} /dev/null
+else	Push sudoargs ${1+"$@"}
+fi
 eval "set -- a $sudoargs"
 shift
 
-# Fill socket:
+# Fill fifo:
 
-if [ -n "${socket:++}" ]
+if [ -n "${fifo:++}" ]
 then	{
-		printf '%s\n%s' "${#transfer}" "$transfer" >"$socket"
+		printf '%s\n%s' "${#transfer}" "$transfer" >"$fifo"
 		RmTemp
-		[ x"$chownpts" = x'1' ] || ClearMyTraps
 	} &
 fi
 
-if [ x"$my_traps" = x'-' ]
+if [ -z "$tmpdir" ]
 then	exec sudo ${1+"$@"}
 	Fatal 'cannot exec sudo'
 fi
+# Clearing the trap is a race, but in the worst case we leave tmpdir.
+# This is better than removing tmpdir possibly twice (if it was already
+# done by the background job): The latter might perhaps be exploited, since
+# an attacker knows that we will remove a dir whose name is then known and
+# which might be prepared then writable by the attacker.
+ClearTrap
 sudo ${1+"$@"}
 retvalue=$?
+[ -z "${fifo:++}" ] || ! test -p "$fifo" || {
+	# If the fifo still exists, we empty it to finish our background job
+	# and thus to clean tmpdir: Avoid removing tmpdir twice as noted above.
+	cat -- "$fifo" >/dev/null
+	wait
+}
 exit $retvalue
